replicaCount: 1

image:
  repository: docker.io/chenyuxudocker/users
  tag: 0.1.0
  pullPolicy: IfNotPresent

imagePullSecrets: []

server:
  port: 8080

database:
  host: 192.168.71.200
  port: 3306
  username: root
  password: "123"
  name: test
  charset: utf8mb4
  parseTime: true
  loc: Local

service:
  type: NodePort
  port: 80
  nodePort: 31888

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: users.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
