apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "users.fullname" . }}-config
  labels:
    {{- include "users.labels" . | nindent 4 }}
data:
  config.toml: |
    [server]
    host = "0.0.0.0"
    port = {{ .Values.server.port }}

    [database]
    host = {{ .Values.database.host | quote }}
    port = {{ .Values.database.port }}
    username = {{ .Values.database.username | quote }}
    password = ""
    name = {{ .Values.database.name | quote }}
    charset = {{ .Values.database.charset | quote }}
    parse_time = {{ .Values.database.parseTime }}
    loc = {{ .Values.database.loc | quote }}
